//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class pilotvardiya
{
    public int id { get; set; }
    public Nullable<int> kapno { get; set; }
    public string varno { get; set; }
    public Nullable<int> toplamissayisi { get; set; }
    public Nullable<decimal> toplamissuresi { get; set; }
    public Nullable<decimal> toplamdinlenme { get; set; }
    public Nullable<decimal> yorulma { get; set; }
    public Nullable<decimal> yorulmalast { get; set; }
    public string kapadisoyadi { get; set; }
    public Nullable<double> toplamzihyor { get; set; }
    public Nullable<decimal> lastday { get; set; }
    public Nullable<decimal> lastseven { get; set; }
    public Nullable<double> yedekbir { get; set; }
    public Nullable<double> yedekiki { get; set; }
    public Nullable<int> sevensayi { get; set; }
    public Nullable<int> daysayi { get; set; }
    public Nullable<int> yorgungitteni { get; set; }
    public Nullable<int> yorgungitalli { get; set; }
    public Nullable<decimal> Percentage { get; set; }
    public string owa { get; set; }
    public string girisist { get; set; }

    public Nullable<decimal> range1 { get; set; }
    public Nullable<decimal> range2 { get; set; }
    public Nullable<decimal> range3 { get; set; }

    public string varidbul { get; set; }
    public string embul { get; set; }



}
