//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class vardiyadetay
{
    public int id { get; set; }
    public Nullable<int> kapno { get; set; }
    public Nullable<int> degismecikapno { get; set; }
    public string varno { get; set; }
    public string gemiadi { get; set; }
    public string bayrak { get; set; }
    public string grt { get; set; }
    public string tip { get; set; }
    public string binisyeri { get; set; }
    public string binisrihtim { get; set; }
    public string inisyeri { get; set; }
    public string inisrihtim { get; set; }
    public string istasyoncikis { get; set; }
    public string pob { get; set; }
    public string poff { get; set; }
    public string istasyongelis { get; set; }
    public string manevraiptal { get; set; }
    public string varid { get; set; }
    public Nullable<int> imono { get; set; }
    public Nullable<decimal> rangeleft { get; set; }
    public Nullable<decimal> rangerest { get; set; }
    public Nullable<decimal> rangework { get; set; }
    public string notlar { get; set; }
    public string talepno { get; set; }
    public string jnot { get; set; }
    public string rom1 { get; set; }
    public string rom2 { get; set; }
    public string rom3 { get; set; }
    public string rom4 { get; set; }
    public string calsaat1 { get; set; }
    public string calsaat2 { get; set; }
    public string acente { get; set; }
    public string oper { get; set; }
    public string mboat { get; set; }
    public string rom5 { get; set; }
    public string calsaat3 { get; set; }
    public string calsaat4 { get; set; }



    public Nullable<DateTime> orderbay { get; set; }
    public Nullable<DateTime> DTpob { get; set; }
    public string pilotismi { get; set; }
    public string tipi { get; set; }
}
