//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class isliste
{
    public int id { get; set; }
    public Nullable<int> imono { get; set; }
    public string gemiadi { get; set; }
    public string demiryeri { get; set; }
    public string kalkislimani { get; set; }
    public string kalkisrihtimi { get; set; }
    public string yanasmalimani { get; set; }
    public string yanasmarihtimi { get; set; }
    public string eta { get; set; }
    public string etb { get; set; }
    public string etd { get; set; }
    public string bowt { get; set; }
    public string strnt { get; set; }
    public string bayrak { get; set; }
    public string grt { get; set; }
    public string tip { get; set; }
    public string loa { get; set; }
    public string draft { get; set; }
    public string bilgi { get; set; }
    public string tehlikeliyuk { get; set; }
    public string acente { get; set; }
    public string fatura { get; set; }
    public string notlar { get; set; }
    public string talepno { get; set; }
    public string nedurumda { get; set; }
    public string nedurumdaopr { get; set; }
    public string gizlegoster { get; set; }
    public string kayitzamani { get; set; }
    public string kaydeden { get; set; }
    public string bowok { get; set; }
    public string pratika { get; set; }
    public string pratikano { get; set; }
    public DateTime orderbay { get; set; }
    public string lcbno { get; set; }
    public string lcbdest { get; set; }
    public string lcbdate { get; set; }
    public string lybyol { get; set; }
}
