//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class pilotlar
{
    public int kapno { get; set; }
    public string kapadi { get; set; }
    public string kapsoyadi { get; set; }
    public string eposta { get; set; }
    public string sifre { get; set; }
    public string tel1 { get; set; }
    public string tel2 { get; set; }
    public string dogumtar { get; set; }
    public string dogumyer { get; set; }
    public string address { get; set; }
    public string yetki { get; set; }
    public Nullable<int> kapsirano { get; set; }
    public string isegiristarihi { get; set; }
    public string kidemliolmatarihi { get; set; }
    public string emeklitarihi { get; set; }
    public string kidem { get; set; }
    public string izinde { get; set; }
    public string izinbasla { get; set; }
    public string izinbit { get; set; }
    public Nullable<System.DateTime> izinbasladate { get; set; }
    public string emekli { get; set; }
    public string varid { get; set; }
    public string girisistasyon { get; set; }
    public string cikisistasyon { get; set; }
    public string respist { get; set; }
    public string durum { get; set; }
    public string varno { get; set; }
    public string degismeciadi { get; set; }
    public string degismecisoyadi { get; set; }
    public Nullable<int> degismecikapno { get; set; }
    public string gemiadi { get; set; }
    public string bayrak { get; set; }
    public string grt { get; set; }
    public string tip { get; set; }
    public string binisyeri { get; set; }
    public string binisrihtim { get; set; }
    public string inisyeri { get; set; }
    public string inisrihtim { get; set; }
    public string istasyoncikis { get; set; }
    public string Pob { get; set; }
    public string Poff { get; set; }
    public string istasyongelis { get; set; }
    public string gemiatamazamani { get; set; }
    public string ilkkayitzamani { get; set; }
    public Nullable<decimal> Percentage { get; set; }
    public string pilotismi { get; set; }
    public Nullable<int> toplamissayisi { get; set; }
    public string toplamissuresi { get; set; }
    public string toplamdinlenme { get; set; }
    public string owa { get; set; }
    public Nullable<decimal> yorulma { get; set; }

    public string izinbasla2 { get; set; }
    public string izinbit2 { get; set; }
}
